name: example_flutter
description: An example project for flutter-desktop-embedding.

version: 0.1.0

environment:
  sdk: '>=2.5.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  storyboard: ^0.0.4


flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Drawkcab
      fonts:
        - asset: fonts/Drawkcab-Regular.ttf
          weight: 100
    - family: Overpass
      fonts:
        - asset: fonts/overpass-mono/overpass-mono-light.otf
          weight: 100
        - asset: fonts/overpass-mono/overpass-mono-regular.otf
          weight: 200
        - asset: fonts/overpass-mono/overpass-mono-semibold.otf
          weight: 300
        - asset: fonts/overpass-mono/overpass-mono-bold.otf
          weight: 400
